### ISSUE TITLE
Warning with update part : not working ?

### ISSUE THREAD

**Issue by gregguittard** [bitseed-org/bitseed#1]
Just tried to update to lnd 0.5 : seems to get some problems.

There's no installation of the new version, my node keeps going on lnd 0.41.
If i log into root, i can install lnd 0.5, but lnd 0.5 is showing with lnd --version only if logged in root user.

For more entertainement, i deleted macaroon.admin, but it seems that there's no new generation of macaroons files.

Seems that the CLI command right there isn't working :
bitcoin@bitseed3:~/download$ sudo install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-386-v0.5-beta/*

Problem seems to come from lnd.service. I got this : 
bitcoin@bitseed3:~$ systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-09-16 22:52:02 CST; 28s ago
  Process: 6388 ExecStart=/usr/local/bin/lnd --externalip=${PUBLICIP} (code=exited, status=1/FAILURE)
 Main PID: 6388 (code=exited, status=1/FAILURE)

Sep 16 22:52:02 bitseed3 systemd[1]: lnd.service: Unit entered failed state.
Sep 16 22:52:02 bitseed3 systemd[1]: lnd.service: Failed with result 'exit-code'.

So it's possible to unlock wallet, but no new generation of macaroon.

So for now, if someone as an idea of what to do, or at least modifying the read.me in order to correct the installation and updating processes.

**Comment by gregguittard** [comment]
bitcoin@bitseed3:/usr$ cd /usr/local
bitcoin@bitseed3:/usr/local$ cd /usr/local/bin
bitcoin@bitseed3:/usr/local/bin$ ls -la
total 39552
drwxr-xr-x  2 root    root        4096 Sep 16 23:06 .
drwxr-xr-x 11 root    root        4096 Jul 26 02:06 ..
-rwxr-xr-x  1 root    root         322 May 17 00:03 getpublicip.sh
lrwxrwxrwx  1 root    root          23 May 13 22:06 go -> /usr/lib/go-1.10/bin/go
-rwxr-xr-x  1 root    root        3901 Jun  8 04:37 lnbalance
-rwxr-xr-x  1 root    root        3273 Jun  8 04:38 lnchannels
-rwxr-xr-x  1 bitcoin bitcoin 13214751 Sep 16 23:06 lncli
-rwxr-xr-x  1 bitcoin bitcoin 27260816 Sep 16 23:06 lnd
lrwxrwxrwx  1 root    root          39 Jun  8 04:42 raspibolt -> /etc/update-motd.d/20-raspibolt-welcome

Maybe here ?

**Comment by john-light** [comment]
@gregguittard I just published a new guide for installing LND on Bitseed 3, see if this one works better:

https://github.com/bitseed-org/bitseed/blob/master/labs/lightning/light_ln_guide.md
